import Taro from '@tarojs/taro';
export default {
  hmGroupInfoCard: {
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    width: Taro.pxTransform(750),
    height: Taro.pxTransform(469)
  },
  container: {
    display: 'flex',
    alignItems: 'flex-start',
    flexDirection: 'column',
    justifyContent: 'center',
    borderRadius: Taro.pxTransform(39),
    boxShadow: '0px 10px 30px rgba(209, 213, 223, 0.50)',
    backgroundColor: '#ffffff',
    width: Taro.pxTransform(721),
    height: Taro.pxTransform(392)
  },
  title: {
    boxSizing: 'border-box',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingRight: Taro.pxTransform(62),
    paddingLeft: Taro.pxTransform(58),
    width: Taro.pxTransform(721)
  },
  titleText: {
    opacity: 1,
    width: Taro.pxTransform(275),
    height: Taro.pxTransform(62),
    lineHeight: Taro.pxTransform(62),
    whiteSpace: 'pre',
    color: '#141821',
    fontFamily: 'Helvetica',
    fontSize: Taro.pxTransform(51),
    fontWeight: 'normal'
  },
  titleIcon: { marginTop: Taro.pxTransform(56), width: Taro.pxTransform(35), height: Taro.pxTransform(8) },
  detail: {
    opacity: 1,
    marginTop: Taro.pxTransform(8),
    marginLeft: Taro.pxTransform(58),
    maxWidth: Taro.pxTransform(639),
    height: Taro.pxTransform(47),
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    lineHeight: Taro.pxTransform(47),
    whiteSpace: 'pre',
    color: '#858997',
    fontFamily: 'Helvetica',
    fontSize: Taro.pxTransform(31),
    fontWeight: 'normal'
  },
  bottom: {
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    marginTop: Taro.pxTransform(58),
    width: Taro.pxTransform(719),
    height: Taro.pxTransform(97)
  },
  memberA: {
    boxSizing: 'border-box',
    display: 'flex',
    position: 'relative',
    alignItems: 'center',
    flexDirection: 'row',
    marginLeft: Taro.pxTransform(58),
    borderWidth: '2px',
    borderStyle: 'solid',
    borderRadius: Taro.pxTransform(49),
    borderColor: 'rgba(255,255,255,1.00)',
    backgroundColor: '#d9f2ec',
    paddingRight: Taro.pxTransform(33),
    paddingLeft: Taro.pxTransform(33),
    height: Taro.pxTransform(97)
  },
  memberAText: {
    opacity: 1,
    lineHeight: Taro.pxTransform(41),
    whiteSpace: 'nowrap',
    color: '#00cd98',
    fontFamily: 'Helvetica',
    fontSize: Taro.pxTransform(27),
    fontWeight: 'normal'
  },
  memberB: {
    boxSizing: 'border-box',
    display: 'flex',
    position: 'absolute',
    top: Taro.pxTransform(0),
    left: Taro.pxTransform(136),
    alignItems: 'center',
    flexDirection: 'row',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderRadius: Taro.pxTransform(49),
    borderColor: 'rgba(255,255,255,1.00)',
    backgroundColor: '#eeeeff',
    paddingRight: Taro.pxTransform(29),
    paddingLeft: Taro.pxTransform(29),
    height: Taro.pxTransform(97)
  },
  memberBText: {
    opacity: 1,
    lineHeight: Taro.pxTransform(41),
    whiteSpace: 'nowrap',
    color: '#5351fb',
    fontFamily: 'Helvetica',
    fontSize: Taro.pxTransform(27),
    fontWeight: 'normal'
  },
  memberC: {
    boxSizing: 'border-box',
    display: 'flex',
    position: 'absolute',
    top: Taro.pxTransform(0),
    left: Taro.pxTransform(214),
    alignItems: 'center',
    flexDirection: 'row',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderRadius: Taro.pxTransform(49),
    borderColor: 'rgba(255,255,255,1.00)',
    backgroundColor: '#fbf0c8',
    paddingRight: Taro.pxTransform(31),
    paddingLeft: Taro.pxTransform(31),
    height: Taro.pxTransform(97)
  },
  memberCText: {
    opacity: 1,
    lineHeight: Taro.pxTransform(41),
    whiteSpace: 'nowrap',
    color: '#f6b900',
    fontFamily: 'Helvetica',
    fontSize: Taro.pxTransform(27),
    fontWeight: 'normal'
  },
  memberD: {
    boxSizing: 'border-box',
    display: 'flex',
    position: 'absolute',
    top: Taro.pxTransform(0),
    left: Taro.pxTransform(292),
    alignItems: 'center',
    flexDirection: 'row',
    borderWidth: '2px',
    borderStyle: 'solid',
    borderRadius: Taro.pxTransform(49),
    borderColor: 'rgba(255,255,255,1.00)',
    backgroundColor: '#fec4b0',
    paddingRight: Taro.pxTransform(31),
    paddingLeft: Taro.pxTransform(29),
    height: Taro.pxTransform(97)
  },
  memberDText: {
    opacity: 1,
    lineHeight: Taro.pxTransform(41),
    whiteSpace: 'nowrap',
    color: '#f64000',
    fontFamily: 'Helvetica',
    fontSize: Taro.pxTransform(27),
    fontWeight: 'normal'
  },
  members: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    opacity: 1,
    marginLeft: Taro.pxTransform(263),
    width: Taro.pxTransform(175),
    height: Taro.pxTransform(41),
    lineHeight: Taro.pxTransform(41),
    whiteSpace: 'pre',
    color: '#c3c6d1',
    fontFamily: 'Helvetica',
    fontSize: Taro.pxTransform(27),
    fontWeight: 'normal'
  }
};
